import './globals.css'

export const metadata = {
  title: 'Google Clone Next js 13 why',
  description: 'Generated by create next app',
  content:'width=device-width, initial-scale = 1',
  name:"viewport"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
